name: Dynamisk-rekruttering
favicon: null
layout_spectrum: 0.7095252173021436
typography_spectrum: 0.07851010910235345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7465626813936979
  lightness: 0.7576949349604547
  saturation: 0.48537887423299253
  rhythmicContrast: 0.3191840169019997
purpose: []
